Updating lib ver to main for all jenkinsfile
opensearch-project/opensearch-build-libraries pull request #10
Opened 2022-09-28 23:14 UTC by jordarlu

Signed-off-by: Jeff Lu <chunglu@amazon.com>

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-28 23:16 UTC, gaiksaya commented
These tests are for this repository and should not affect any downstream libraries/files. So we are good @jordarlu @zelinh @peterzhuamazon

2022-09-28 23:18 UTC, gaiksaya approved these changes

2022-09-29 15:37 UTC, dblock approved these changes

2022-09-29 15:54 UTC, prudhvigodithi requested changes
I see the groovy tests failing, @jordarlu can you please take a look.

2022-09-30 17:41 UTC, closed without merging