License Header checker
opensearch-project/opensearch-build-libraries pull request #13
Opened 2022-10-06 22:08 UTC by Divyaasm

Signed-off-by: Divya Madala <divyaasm@amazon.com>

### Description
License Header Checker for opensearch-build-libraries Repository

### Issues Resolved
Added missing license headers and created a license-header-checker workflow.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-06 23:22 UTC, peterzhuamazon approved these changes

2022-10-06 23:24 UTC, peterzhuamazon requested changes
Hi @Divyaasm I think you missed the .jenkinsfile here.
Probably the same in the build repo.

Thanks.

2022-10-06 23:45 UTC, Divyaasm commented
> Hi @Divyaasm I think you missed the .jenkinsfile here. Probably the same in the build repo.
> 
> Thanks.

I didn't add any check for Jenkinsfile in the buildrepo. So I did the same here. I can add a condition if required for jenkinsfile.
Please let me know.

2022-10-10 17:50 UTC, peterzhuamazon approved these changes

2022-10-10 17:50 UTC, merged